FROM python:3.12.3

WORKDIR /app

COPY requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt

COPY src/inferencia.py src/
COPY src/preprocesamiento.py src/
COPY src/api.py src/

EXPOSE 8000

WORKDIR /app/src

CMD ["python", "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
